{%- if cookiecutter.language == "c++" -%}
{%- include 'Dockerfiles/Dockefile.cpp' %}
{%- elif cookiecutter.language == "python2.7" -%}
{%- include 'Dockerfiles/Dockerfile.python27' %}
{%- elif cookiecutter.language == "R" -%}
{%- include 'Dockerfiles/Dockerfile.R' %}
{%- elif cookiecutter.language == "python3" -%}
{%- include 'Dockerfiles/Dockerfile.python3' %}
{%- endif -%}
