FROM python:3
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
RUN pip install --upgrade pip
COPY ./src
COPY ./data
COPY requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
